@startuml class
customer"0..n" -->"1..n"shop : สั่งซื้อหนังสือ
shop"1..n" *-- "1..1""data server"
shop"1..n" -->"1..n"publisher : สั่งทำหนังสือ
"data server""1..1" <--"1..2" Owner :manage
Owner"1..2" --o "1..1"shop
class customer { 
    +ชื่อ
    +รหัสประจำตัวประชาชน
    +ที่อยุ่
    +นามสกุล
    +เบอร์โทรศัพท์
    เลือกซื้อหนังสือ()
}
class shop{
    +ชื่อร้าน
    -จำนวนพนักงาน
    ขายหนังสือ()
}
class publisher{
    +ชื่อ
    -จำนวนพนักงาน
    จัดทำหนังสือ()
    ส่งหนังสือ()
}

class "data server"{
    +ชื่อ
    -ความจุ
    เก็บข้อมูล()
}
Class Owner{
    +ชื่อ
    +นามสกุล
    อ่านรายการสรุป()
    ปรับปรุงระบบ()

}

@enduml