@startuml Register

actor User
participant "Register" as R
participant "Login" as L

User -> R : ส่งข้อมูลที่ต้องใช้ในการสมัคร
R -> R : เช็คข้อกำหนดในการตั้งชื่อ,รหัสผ่าน
R -> User : (ถ้าไม่ครบตามข้อกำหนด) กรุณาแก้ไขให้ถูกตั้ง
R -> User : (ถ้าเป็นไปตามข้อกำหนด) สมัครสมาชิกเรียบร้อย
User -> L : ล็อคอินเข้าสู่ระบบอัตโนมัติ

@enduml